jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 654654162109.dkr.ecr.us-east-1.amazonaws.com

      - name: Build & Push Docker image
        run: |
          docker build -t app .
          docker tag app:latest 654654162109.dkr.ecr.us-east-1.amazonaws.com/app:latest
          docker push 654654162109.dkr.ecr.us-east-1.amazonaws.com/app:latest
