name: Node.js CI/CD

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install deps
      run: npm install
      working-directory: ./app

    - name: Run tests
      run: npm test || echo "Skipping tests"
      working-directory: ./app

    - name: Build Docker image
      run: docker build -t my-app .
      working-directory: ./app

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          docker rm -f my-app || true
          docker pull my-app || true
          docker run -d -p 80:3000 --name my-app my-app
