name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 654654162109.dkr.ecr.us-east-1.amazonaws.com

      - name: Build & Push Docker image
        run: |
          docker build -t app .
          docker tag app:latest 654654162109.dkr.ecr.us-east-1.amazonaws.com/app:latest
          docker push 654654162109.dkr.ecr.us-east-1.amazonaws.com/app:latest

      - name: Terraform Apply
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve
